apiVersion: apps/v1beta1
kind: Service             
apiVersion: v1            
metadata:                 
  name: test-gke
spec:                     
  selector:               
    app: test-gke         
  ports:                  
  - protocol: TCP         
    targetPort: 8080      
    port: 8080             
    name: http            
  - protocol: TCP         
    targetPort: 22        
    port: 22              
    name: ssh             
  type: LoadBalancer      

